---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.shadowmanager
ComponentDescription: AWS Greengrass Shadow Manager
ComponentPublisher: AWS
ComponentVersion: '0.0.0'
ComponentType: aws.greengrass.plugin
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: s3://gg-dev-artifacts/$componentName/$platform.os/$version/aws.greengrass.shadowmanager.jar
