#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -U -ntp clean verify -f uat/pom.xml
      - curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > /tmp/greengrass-nucleus-latest.zip
      - java -Dggc.archive=/tmp/greengrass-nucleus-latest.zip
        -Dtags=ShadowManager -Dggc.install.root=$CODEBUILD_SRC_DIR -Dggc.log.level=INFO -Daws.region=$AWS_REGION
        -jar uat/testing-features/target/greengrass-shadow-manager-testing-features.jar

artifacts:
  files:
    - 'testResults/**/*'
  name: 'ShadowManagerUatLinuxLogs.zip'

reports:
  uat-reports:
    files:
      - "TEST-greengrass-results.xml"
    file-format: "JUNITXML"
